require 'simplecov'
SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
require_relative '../lib/enrollment'
require_relative '../lib/statewide_test_repository'
require_relative '../lib/district_repository'
require_relative '../lib/load_data'
require_relative '../lib/district'
require_relative '../lib/enrollment_repository'
require_relative '../lib/enrollment'
require_relative '../lib/statewide_test'
require_relative '../lib/headcount_analyst'
